type = "javascript"
account_id = "b989c18bd2f4829d4997fa5ce5ba66aa"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
name = "autorole"
kv_namespaces = [
    { binding = "GROUPS", id = "2075a5dbcf3b4b749c159820e6107477", preview_id = "2075a5dbcf3b4b749c159820e6107477" }
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
