type = "javascript"
account_id = "b989c18bd2f4829d4997fa5ce5ba66aa"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
name = "autorole-dev"
kv_namespaces = [
    { binding = "GROUPS", id = "6e146432900c4f179c62cd8fc8e3fc45", preview_id = "6e146432900c4f179c62cd8fc8e3fc45" }
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
